version: '3.8'

services:
  slackliner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slackliner-service
    read_only: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Redis configuration
      - REDIS_ADDR=${REDIS_ADDR:-host.docker.internal:6379}
      - REDIS_PASSWORD=
      - REDIS_LIST_KEY=slack_messages
      # Slack configuration
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
    restart: unless-stopped
